import { Router, type IRouter } from "express";
import healthRouter from "./health";
import geminiRouter from "./gemini";
import driveRouter from "./drive";
import contentRouter from "./content";
import studioRouter from "./studio";
import youtubeRouter from "./youtube";
import tiktokRouter from "./tiktok";
import instagramRouter from "./instagram";
import linkedinRouter from "./linkedin";
import xRouter from "./x";
import facebookRouter from "./facebook";
import communityRouter from "./community";
import ideasRouter from "./ideas";
import analyticsRouter from "./analytics";
import inspirationsRouter from "./inspirations";
import onboardingRouter from "./onboarding";
import savedViewsRouter from "./saved-views";
import socialRouter from "./social";
import libraryRouter from "./library";
import notificationsRouter from "./notifications";
import collaborationRouter from "./collaboration";
import connectionsRouter from "./connections";
import settingsRouter from "./settings";
import transcriberRouter from "./transcriber";
import credentialsRouter from "./credentials";
import calendarRouter from "./calendar";
import hubRouter from "./hub";
import hrRouter from "./hr";
import ticketsRouter from "./tickets";
import adminUsersRouter from "./admin-users";

const router: IRouter = Router();

router.use(healthRouter);
router.use(geminiRouter);
router.use(driveRouter);
router.use(contentRouter);
router.use(studioRouter);
router.use(youtubeRouter);
router.use(tiktokRouter);
router.use(instagramRouter);
router.use(linkedinRouter);
router.use(xRouter);
router.use(facebookRouter);
router.use(communityRouter);
router.use(ideasRouter);
router.use(analyticsRouter);
router.use(inspirationsRouter);
router.use(onboardingRouter);
router.use(savedViewsRouter);
router.use(socialRouter);
router.use(libraryRouter);
router.use(notificationsRouter);
router.use(collaborationRouter);
router.use(connectionsRouter);
router.use(settingsRouter);
router.use(transcriberRouter);
router.use(credentialsRouter);
router.use(calendarRouter);
router.use(hubRouter);
router.use(hrRouter);
router.use(ticketsRouter);
router.use(adminUsersRouter);

export default router;
