import { createContext, useContext, useState, useCallback, type ReactNode } from "react";

type Lang = "es" | "en";

const T = {
  es: {
    // Login
    loginSubtitle: "Panel de administración de contenido",
    loginGoogle: "Iniciar sesión con Google",
    loginTestLink: "Iniciar con cuenta de prueba",
    loginTestLabel: "Cuenta de prueba",
    loginUser: "Usuario",
    loginPassword: "Contraseña",
    loginEnter: "Entrar",
    loginOnlyAuth: "Solo usuarios autorizados pueden acceder",
    loginAgree: "Al iniciar sesión, aceptas nuestros",
    loginTerms: "Términos de Servicio",
    loginAnd: "y",
    loginPrivacy: "Política de Privacidad",
    loginConnError: "Error de conexión",

    // Nav
    navHome: "Inicio",
    navPosts: "Publicaciones",
    navAccounts: "Cuentas Sociales",
    navVideos: "Gestor de Videos",
    navInsights: "Insights",
    navLibrary: "Biblioteca",
    navCovers: "Portadas",
    navStories: "Historias",
    navDescriptions: "Descripciones",
    navDrive: "Drive",
    navStudio: "Estudio",
    navTranscriber: "Transcriptor",
    navTeam: "Equipo",
    navHelp: "Ayuda",
    navSettings: "Ajustes",
    navHub: "Hub Ejecutivo",
    navLogout: "Cerrar Sesión",
    navSearch: "Buscar o ejecutar...",
    navMenu: "Menú",
    navMore: "Más",
    navCloseMenu: "Cerrar menú",
    navOpenMenu: "Abrir menú",

    // Ajustes
    ajustesTitle: "Ajustes",
    ajustesSubtitle: "Gestiona las credenciales de API de cada red social. Los valores se encriptan con AES-256-GCM antes de guardarse en la base de datos.",
    ajustesSecurity: "Almacenamiento seguro",
    ajustesSecurityDesc: "Los valores ingresados se encriptan antes de guardarse. Nunca se muestran en claro: solo puedes sobreescribirlos o eliminarlos. Las credenciales marcadas como 'Entorno' están configuradas en el servidor y no son editables desde aquí.",

    // Cuentas
    cuentasTitle: "Cuentas Sociales",
    cuentasSubtitle: "Conecta tus redes sociales para publicar y traer estadísticas a tu Inicio.",
    cuentasHint: "Conecta cada red para publicar y traer estadísticas. Algunas redes (Facebook, Instagram) usan credenciales de servidor: aparecen como conectadas si el administrador configuró las llaves correspondientes.",
    cuentasNoConnected: "Aún no has conectado ninguna red social",
    cuentasNoConnectedDesc: "Comienza por conectar al menos una red abajo. Cada red habilita publicar videos, descripciones e historias en su plataforma.",
    cuentasConnect: "Conectar",
    cuentasDisconnect: "Desconectar",
    cuentasReconnect: "Reconectar ahora",
    cuentasRefresh: "Refrescar estado",
    cuentasNotConnected: "No conectado",
    cuentasNoSession: "Sin sesión activa",
    cuentasNoMethod: "Sin método de conexión disponible.",
    cuentasServerManaged: "Configurar credenciales en los secretos del servidor.",

    // State badges
    badgeActive: "Activo",
    badgeExpiring: "Por expirar",
    badgeExpired: "Expirada",
    badgeRevoked: "Revocada",
    badgeUnknown: "Sin datos",

    // Expiry messages
    expiresOn: "Vence el",
    expiringSoon: (days: number) => `La sesión caduca en ${days} día${days === 1 ? "" : "s"}. Reconecta pronto para evitar fallas.`,
    sessionInvalid: "La sesión ya no es válida. Reconecta tu cuenta para volver a publicar.",

    // Network descriptions
    descFacebook: "Página de Facebook conectada a nivel servidor",
    descInstagram: "Cuenta de Instagram Business vinculada a la Página",
    descLinkedin: "Personal o Página de empresa",
    descX: "Cuenta de X (Twitter)",
    descTiktok: "Modo sandbox: el video llega como borrador",
    descYoutube: "Conecta para subir videos a YouTube, acceder a Drive y Google Calendar",

    // Network server notes
    noteFacebook: "Facebook usa credenciales de System User permanentes configuradas en el servidor.",
    noteInstagram: "Instagram requiere credenciales de Meta a nivel de servidor (INSTAGRAM_ACCESS_TOKEN). Pídele al administrador que las configure en los secretos del proyecto.",

    // TikTok meta
    tiktokSandbox: "Conectado (sandbox)",

    // Instagram meta
    followers: "seguidores",
    posts: "posts",

    // LinkedIn
    linkedinChangeIdentity: "Cambiar identidad de publicación",
    linkedinChooseHow: "Elige cómo publicar en LinkedIn:",
    linkedinPersonal: "Perfil personal",
    linkedinSearching: "Buscando páginas...",
    linkedinEnterPage: "Ingresa la URL o nombre de tu Página de empresa en LinkedIn:",
    linkedinNotFound: "No se encontró esa página. Verifica el nombre exacto en linkedin.com/company/...",
    linkedinSelect: "Seleccionar →",
    linkedinCompanyPage: "Página de empresa",

    // X
    xConnected: "Cuenta de X conectada",

    // Facebook
    fbConnected: "Página de Facebook conectada",

    // LinkedIn connected meta
    linkedinCompanyPageMeta: "Página de empresa",
    linkedinPersonalMeta: "Perfil personal",

    // Lang toggle
    langLabel: "EN",

    // ── Videos page ──────────────────────────────────────────────
    stepInfo: "Información Básica",
    stepInfoShort: "Info",
    stepCover: "Portada",
    stepCoverShort: "Portada",
    stepTikTokInstagram: "TikTok e Instagram",
    stepTikTokShort: "TikTok/IG",
    stepYouTube: "YouTube",
    stepYouTubeShort: "YouTube",
    stepLinkedInX: "LinkedIn y X",
    stepLinkedInXShort: "LinkedIn/X",
    stepReview: "Revisar y Programar",
    stepReviewShort: "Programar",
    stepComments: "Comentarios y Aprobación",
    stepCommentsShort: "Comentarios",

    searchPlaceholder: "Buscar por título, descripción o red...",
    filterAllStatuses: "Todos los estados",
    filterDraft: "Borrador",
    filterCoverReady: "Portada lista",
    filterScheduled: "Programado",
    filterPublished: "Publicado",
    filterPartial: "Parcial",
    filterError: "Con error",
    filterAllNetworks: "Todas las redes",
    filterAllMonths: "Todos los meses",
    filterAllCampaigns: "Todas las campañas",
    filterNoCampaign: "Sin campaña",
    filterAllTemplates: "Todas las plantillas",
    filterNoTemplate: "Sin plantilla",
    filterClear: "Limpiar",
    filterClearFilters: "Limpiar filtros",
    noVideos: "Sin videos registrados",
    noVideosDesc: "Crea tu primer video. Te guiaremos paso a paso: información, portada, descripciones por red y revisión final.",
    createFirstVideo: "Crear primer video",
    noResults: "Ningún video coincide con tus filtros.",
    showingOf: (showing: number, total: number) => `Mostrando ${showing} de ${total}`,
    videosSelected: (n: number) => `${n} seleccionado${n === 1 ? "" : "s"}`,
    videosCount: (n: number) => `${n} video${n === 1 ? "" : "s"}`,

    statusPublished: "Publicado",
    statusPartial: "Parcial",
    statusError: "Error",
    statusScheduled: "Programado",
    statusReady: "Listo",
    statusDraft: "Borrador",
    statusComplete: (pct: number) => `${pct}% completo`,

    wizardNewVideo: "Nuevo Video",
    wizardCompleteAll: "Completa todos los pasos para programar en las 6 plataformas",
    wizardAutoGenerating: "Generando contenido con IA para todas las plataformas...",
    wizardSaving: "Guardando",
    wizardUnsaved: "Sin guardar",
    wizardSavingTooltip: "Guardando...",
    wizardUnsavedTooltip: "Hay cambios sin guardar",
    wizardBack: "Volver al listado",
    wizardBackShort: "Volver",
    wizardDelete: "Eliminar",

    btnSave: "Guardar",
    btnCancel: "Cancelar",
    btnContinue: "Continuar",
    btnContinueWithoutCover: "Continuar sin portada",
    btnCreateContinue: "Crear y Continuar",
    btnSaveContinue: "Guardar y Continuar",
    btnPrev: "Anterior",
    btnGenerate: "Generar con IA",
    btnGenerating: "Generando...",
    btnRegenerate: "Regenerar con IA",
    btnUpload: "Subir portada",
    btnUploading: "Subiendo...",
    btnReplace: "Reemplazar",
    btnRemove: "Quitar",
    btnCopyAll: "Copiar todo",
    btnDownloadTxt: "Descargar .txt",
    btnExportPdf: "Exportar .pdf",
    btnExportingPdf: "Exportando...",
    btnGenerateAI: "✨ Generar con IA",
    btnSchedule: "Programar",
    btnCopy: "Copiar",
    btnChange: "Cambiar",
    btnViewHelp: "Ver ayuda",

    coverTitle: "Portada del Video",
    coverOptional: "(opcional)",
    coverSubtitle: "Sube tu propia portada o genérala con IA. Si no quieres definirla ahora, puedes continuar y volver más tarde.",
    coverReady: "Portada lista",
    coverHowItLooks: "Cómo se verá en cada red",
    coverPromptLabel: "Prompt personalizado para la IA",
    coverPromptActive: "Activo",
    coverPromptDesc: "Escribe instrucciones específicas (estilo, colores, texto en pantalla, escena). Se sobrescribe sobre el prompt por defecto. Déjalo vacío para volver al estilo automático.",
    coverGenerateWithPrompt: "Generar con este prompt",
    coverFileHint: "PNG, JPG o WEBP · La portada es opcional, puedes continuar sin ella.",

    stepInfoTitle: "Información Básica",
    stepInfoSubtitle: "Ingresa los datos principales del video",
    videoTitleLabel: "Título del Video",
    videoDescLabel: "Descripción General",
    saveViewBtn: "Guardar vista actual",
    toastVistaSaved: "Vista guardada",
    toastVistaDeleted: "Vista eliminada",
    toastVideoCreated: "Video creado",
    toastVideoCreatedDesc: "Generando contenido con IA en segundo plano...",
    toastVideoDeleted: "Video eliminado",
    toastCoverGenerated: "Portada generada",
    toastCoverUploaded: "Portada subida",
    toastRetryFromInfo: "Reintenta desde el paso de Información.",
    fromGoogleDrive: "Desde Google Drive",
    fromGoogleDriveHint: "Selecciona un video de tu Drive",
    uploadOrDrag: "Subir o arrastrar archivo",
    uploadOrDragHint: (mb: number) => `MP4, MOV · Máx ${mb} MB`,
    linkingFromDrive: "Vinculando desde Drive...",
    uploadingToDrive: "Subiendo a Google Drive...",
    uploadCancel: "Cancelar",
    preparing: "Preparando...",

    stepTikTokTitle: "TikTok e Instagram",
    stepTikTokSubtitle: "Escribe las descripciones para TikTok e Instagram. Incluye hashtags y emojis.",
    genTikTokPlaceholder: "descripción de TikTok",
    genInstagramPlaceholder: "descripción de Instagram",
    tiktokCharHint: (n: number) => `Máximo 2200 caracteres · ${n}/2200`,
    instagramCharHint: (n: number) => `Máximo 2200 caracteres · ${n}/2200`,

    stepYouTubeTitle: "YouTube",
    stepYouTubeSubtitle: "Título y descripción para YouTube Shorts. El título es diferente al de TikTok/Instagram.",
    ytTitleLabel: "Título para YouTube",
    ytDescLabel: "Descripción para YouTube",
    genYTTitlePlaceholder: "título de YouTube",
    genYTDescPlaceholder: "descripción de YouTube",
    ytTitlePlaceholder: "Título optimizado para YouTube (máx. 100 caracteres)",
    ytTitleHint: (n: number) => `${n}/100 caracteres`,
    ytDescHint: (n: number) => `${n}/5000 caracteres`,

    stepLinkedInXTitle: "LinkedIn, X y Facebook",
    stepLinkedInXSubtitle: "Textos para LinkedIn (máx. 3000), X (máx. 280) y Facebook (máx. 500). Facebook es opcional.",
    fbDescOptional: "(opcional)",
    genLinkedInPlaceholder: "descripción de LinkedIn",
    genXPlaceholder: "tweet para X",
    linkedinCharHint: (n: number) => `Máximo 3000 caracteres · ${n}/3000`,
    xCharHint: (n: number) => `Máximo 280 caracteres · ${n}/280`,
    fbCharHint: (n: number) => `Máximo 500 caracteres · ${n}/500`,

    reviewTitle: "Revisar y Programar",
    reviewSubtitle: "Revisa todo antes de programar en las 6 plataformas",
    reviewReady: "Listo",
    reviewPending: "Pendiente",
    reviewScheduled: "Programado",
    reviewIncomplete: "Faltan datos por completar",
    reviewIncompleteDesc: "Completa todos los pasos anteriores antes de programar",
    reviewPartiallyPublished: "Publicado parcialmente",
    reviewPublishErrors: "Hubo errores al publicar",
    reviewScheduledSuccess: "Programado en las plataformas configuradas",
    reviewScheduledTime: "Hora programada:",
    reviewImmediateUpload: "Subida Inmediata",
    reviewImmediateSubtitle: "· Se sube ahora, no en la hora programada",
    reviewImmediateSubtitleIG: "· Se sube ahora como Reel público",
    reviewUploadYTNow: "Subir a YouTube ahora",
    reviewUploadTTNow: "Subir a TikTok ahora",
    reviewUploadIGNow: "Subir a Instagram ahora",
    reviewUploadPrivateYT: (name: string) => `Subir "${name}" como Short privado`,
    reviewUploadPrivateTT: (name: string) => `Subir "${name}" como privado`,
    reviewUploadReel: (name: string) => `Subir "${name}" como Reel`,
    reviewSelectFromDrive: "Selecciona un video desde Drive",
    reviewUploadFromDrive: "Subir desde Drive",
    reviewFromDrive: "Desde Drive",
    reviewUploading: "Subiendo...",
    reviewUploadedToYT: "Subido a YouTube",
    reviewUploadedToTT: "Subido a TikTok",
    reviewUploadedToIG: "Subido a Instagram",
    reviewSentToTT: "Enviado",
    reviewPublishedIG: "Publicado",
    reviewThumbnailApplied: "✓ Portada aplicada como miniatura",
    reviewThumbnailError: (e: string) => `⚠ Portada no aplicada: ${e}`,
    reviewViewOnYT: "Ver en YouTube",
    reviewTTSuccessTitle: "Subida exitosa a TikTok",
    reviewTTProcessing: "Procesando en TikTok…",
    reviewTTPublished: "Publicado en TikTok",
    reviewTTFailed: "Error al procesar en TikTok",
    reviewTTPollingStatus: "Verificando estado",
    reviewIGSuccessTitle: "Subida exitosa a Instagram",
    reviewIncludeFacebook: "Incluir Facebook",

    saveViewPlaceholder: "Nombre de la vista",

    // ── Studio page ──────────────────────────────────────────────
    studioListening: "Escuchando",
    studioEndOfScript: "FIN DEL GUION",
    studioMarkedRecorded: "Listo, grabado",
    studioSlow: "Lento",
    studioFast: "Rapido",
    studioSpeakFollow: "Habla y el guion te sigue",
    studioActivatingMic: "Activando microfono...",
    studioCameraError: "Error al iniciar la camara",
    studioCameraPermission: "Verifica los permisos de camara en la configuracion de tu navegador o app",
    studioCameraRetry: "Reintentar",
    studioCameraBack: "Volver",
    studioCameraNotAvailable: "Camara no disponible en este navegador",
    studioCameraTimeout: "La camara tardo demasiado en responder",
    studioInitializingCamera: "Iniciando camara...",
    studioInitializingCameraHint: "Acepta los permisos si aparece un mensaje",
    studioUploadToDrive: "Subir a Drive",
    studioDiscard: "Descartar",
    studioExclude: "Excluir",
    studioInclude: "Incluir",
    studioVoiceReset: "Reiniciando",
    studioVoiceRetry: "Reintentando clip",
    studioProcessingDrive: "Procesando en Drive...",
    studioUploadingBg: "Subiendo en segundo plano",
    studioUploadingBgDesc: (name: string) => `"${name}" se sube. Elige otro video para grabar.`,
    studioUploadedToDrive: (title: string, day: string) => `"${title}" ${day ? `subido → ${day}` : "subido"}`,
    studioUploadErrorDrive: (title: string) => `"${title}" ERROR subiendo`,
    studioVideoMarkedTitle: "Video marcado como grabado",
    studioScriptCopied: "Guion copiado al portapapeles",
    studioIdeaDeleted: "Idea eliminada",
    studioExcellent: "Excelente",
    studioVideoMarkedMsg: "Video marcado como grabado",
    studioStreak: (n: number) => `Racha: ${n} dias`,
    studioFreeRecord: "Grabar libre",
    studioNoScript: "Sin guion, solo tu y la camara",
    studioDayDest: "Destino en Drive",
    studioDayAuto: "Dia: Automatico",
    studioDayLunes: "Lunes",
    studioDayMartes: "Martes",
    studioDayMiercoles: "Miercoles",
    studioDayJueves: "Jueves",
    studioDayViernes: "Viernes",
    studioDaySabado: "Sabado",
    studioDayDomingo: "Domingo",
    studioPublishTime: (time: string) => `Hora de publicacion: ${time} hrs`,
    studioRacha: "Racha",
    studioSemana: "Semana",
    studioMes: "Mes",
    studioDeleting: "Eliminando...",
    studioDelete: "Eliminar",
    studioEmptyTitle: "Tu estudio esta vacio",
    studioEmptyDesc: `Ve a la pestaña "Ideas IA", genera ideas de video y guarda las que te gusten con el bookmark. Apareceran aqui listas para grabar.`,
    studioMotivational: [
      "Hoy es un gran dia para crear contenido",
      "Tu audiencia espera tu proximo video",
      "La constancia es la clave del exito",
      "Cada video te acerca a mas clientes",
      "El contenido que creas hoy, vende manana",
      "Un video al dia mantiene el algoritmo feliz",
      "Tu marca crece con cada video que grabas",
    ],
    videoLinked: "Video vinculado",
    noVideosTitle: "Sin videos registrados",
    studioIdeasTab: "Ideas IA",
    studioTodayHint: (day: string, hour: number) => `Hoy: ${day} (${hour}:00 hrs)`,
    studioReadyToRecord: "Listos para grabar",
    studioRecordedCount: (n: number) => `Grabados (${n})`,
    studioDeleteIdeaTitle: "Eliminar idea",
    studioDeleteIdeaDesc: "Esta accion no se puede deshacer",
    toastInvalidFile: "Archivo no válido",
    toastUploadError: "Error al subir el video",
    toastUploadCancelled: "Subida cancelada",
    bulkChangeStatus: "Cambiar estado...",
    bulkAssignMonth: "Asignar mes",
    autoGenLabel: (label: string) => `Generando ${label} con IA...`,
    descLabelTikTok: "descripción de TikTok",
    descLabelInstagram: "descripción de Instagram",
    descLabelLinkedIn: "descripción de LinkedIn",
    descLabelYouTube: "descripción de YouTube",
    descLabelX: "tweet para X",
    statViews: "Vistas",
    statLikes: "Me gusta",
    statComments: "Comentarios",
    statDuration: "Duración promedio",
    statPlays: "Reproducciones",
    statReach: "Alcance",
    statImpressions: "Impresiones",
    statClicks: "Clics",
    statReactions: "Reacciones",
    statShares: "Compartidos",
    statRetweets: "Retweets",
    statReplies: "Respuestas",
    statQuotes: "Citas",
    wfBorrador: "Borrador",
    wfEnRevision: "En revisión",
    wfAprobado: "Aprobado",
    wfProgramado: "Programado",
    wfPublicado: "Publicado",
    commentsPlaceholder: "Escribe un comentario… usa @email para mencionar a alguien",
    stepTikTokCardTitle: "TikTok e Instagram",
    stepLinkedInXCardTitle: "LinkedIn, X y Facebook",
    stepLinkedInXCardSubtitle: "Textos para LinkedIn (máx. 3000), X (máx. 280) y Facebook (máx. 500). Facebook es opcional.",
    ytTitlePlaceholderFull: "Título optimizado para YouTube (máx. 100 caracteres)",
    ytDescPlaceholderFull: "descripción de YouTube",
    secondaryViewHelp: "Ver ayuda",
    viewNamePlaceholder: "Nombre de la vista",
    csvImportTitle: "Importar videos desde CSV",
    csvImporting: "Importando...",
    csvImportDone: "Importación completada",
    csvImportBtn: (n: number) => `Importar ${n} video${n === 1 ? "" : "s"}`,
    reviewAssignedTo: (name: string) => `Revisión asignada a ${name}`,
    btnComments: "Comentarios",
    btnRequestReview: "Pedir revisión",
    btnRequestChanges: "Solicitar cambios",
    btnApprove: "Aprobar",
    btnApproveSchedule: "Aprobar y programar",
    btnApproveDirect: "Aprobar directamente",
    labelReviewer: "Revisor",
    selectReviewer: "Selecciona un revisor…",
    toastSelectReviewer: "Selecciona un revisor",
    toastReviewRequested: "Revisión solicitada",
    csvNoValidRows: "No hay filas válidas para importar",
    csvPartialError: (created: number, errors: number) => `${created} importados, ${errors} con error`,
    csvImportFailed: "La importación falló",
    csvImportedDraft: (n: number) => `${n} video${n === 1 ? "" : "s"} importados como borrador`,
    csvImportError: "Error en la importación",
    csvRowMissingTitle: "Falta el título",
    csvRowMissingDesc: "Falta la descripción",
    csvRowTitleTooLong: "Título demasiado largo (máx 240)",
    toastCompleteTitle: "Completa el título del video",
    statErrorMsg: "No se pudieron cargar las métricas",
    toastDeleteVideosError: "Error al eliminar videos",
    toastDeleteVideosFailed: "No se pudieron eliminar los videos",
    toastDeleteVideoError: "No se pudo eliminar el video",
    toastCreateVideoError: "Error al crear video",
    toastAttachError: "No se pudo adjuntar el video",
    toastScheduleError: "No se pudo programar",
    toastMarkRecordedError: "No se pudo marcar como grabado",
    toastDeleteIdeaError: "Error al eliminar",
    toastUndoError: "No se pudo deshacer",
    errorNoVideoFile: "No hay archivo de video. Sube uno en el paso 1.",
    errorNoVideoFileDrive: "No hay archivo de video en Drive. Sube uno primero.",
    confirmDeleteVideo: "¿Eliminar este video?",
    confirmBulkDelete: (n: number) => `¿Eliminar ${n} video${n === 1 ? "" : "s"}? Esta acción no se puede deshacer.`,
    btnDelete: "Eliminar",
    ariaDeselect: (title: string) => `Deseleccionar "${title}"`,
    ariaSelect: (title: string) => `Seleccionar "${title}"`,
    reviewNoteLabel: "Nota (opcional)",
    reviewNotePlaceholder: "¿Qué quieres que revise?",
    reviewNoReviewers: "No hay revisores asignados. Ve a /equipo para asignar uno.",
    cameraError: "No se pudo acceder a la camara",
    recordingError: "Error durante la grabacion",
    recordingStartError: "No se pudo iniciar la grabacion",
    browserNoVideo: "Tu navegador no soporta grabacion de video",
    studioNoVideoToUpload: "No hay video para subir",
    studioUploading: (mb: string) => `Subiendo (${mb} MB)...`,
    studioNoVideoRecorded: "No se grabo ningun video",
    labelVideoFile: "Archivo de Video",
    videoUnsupported: "Tu navegador no soporta la reproducción de este video.",
    videoDriveSelected: "Video de Drive seleccionado",
    videoSelected: "Video seleccionado",
    videoAttachedFile: "Archivo adjunto",
    videoWillLinkOnSave: "Se vinculará al guardar",
    uploadPreparing: "Preparando...",
    uploadFromDrive: "Desde Google Drive",
    uploadFromDriveHint: "Selecciona un video de tu Drive",
    uploadSizeHint: (mb: number) => `MP4, MOV · Máx ${mb} MB`,
    coverPromptTitle: "Prompt personalizado para la IA",
    coverPromptPlaceholder: (title: string) => `Ej: Portada vertical 9:16, estilo flat vector amarillo, zorro con lentes apuntando a un gráfico. Texto grande arriba: "${title || "TÍTULO"}".`,
    btnGenerateWithPrompt: "Generar con este prompt",
    uploadNetworkError: "Error de red durante la subida",
    uploadCancelledError: "Subida cancelada",
    csvEmptyError: "El CSV está vacío o sólo tiene encabezados.",
    toastSaveViewError: "No se pudo guardar la vista",
    toastSaveError: (status: number) => `No se pudo guardar (HTTP ${status})`,
    toastCoverError: "Error al generar portada",
    toastCoverEmptyError: "Archivo de portada vacío o inválido",
    toastLoadStatsError: "Error al cargar estadísticas",
    statDialogTitle: (title: string) => `Estadísticas — ${title}`,
    toastAutoSaveError: "No se pudo auto-guardar",
    toastRetry: "Reintenta",
    toastScheduled: (platforms: string) => `¡Programado en las ${platforms}!`,
    toastAutoUpload: (hour: string) => `Se subirá automáticamente a las ${hour} hrs`,
    toastAutoUploadNow: "Se subirá automáticamente ahora",
    platforms6: "6 plataformas",
    platforms5: "5 plataformas",
    videoDescPlaceholder: "¿De qué trata el video?",
    labelMonth: "Mes",
    labelWeek: "Semana",
    labelDay: "Día",
    monthAbbrs: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"] as const,
    dayAbbrs: ["Lun", "Mar", "Mie", "Jue", "Vie", "Sab", "Dom"] as const,
    toastSavePromptError: "No se pudo guardar el prompt",
    toastSavePromptErrorTitle: "Error guardando prompt",
    uploadHttpError: (status: number) => `Error al subir (HTTP ${status})`,
    teleprompterEnd: "FIN DEL GUION",
    btnMarkRecorded: "Listo, grabado",
    videoRecordedLabel: "Video grabado",
    headerGestorVideos: "Gestor de Videos",
    headerGestorDesc: "Tu editora puede completar cada video paso a paso sin salir de aquí.",
    btnNewVideo: "Nuevo Video",
    savedViewsLabel: "Vistas guardadas",
    pendingReviewsLabel: "Mis revisiones pendientes",
    noSavedViews: "Aún no tienes vistas. Aplica filtros y guarda una para acceder rápido.",
    csvInstructions: "Sube un archivo .csv con columnas title y description (opcional: mes, semana, día, videoNumber, hora, campaignId, templateId). Los videos quedan como borrador.",
    btnTemplate: "Plantilla",
    csvDragHere: "Arrastra tu CSV aquí o haz clic para seleccionar",
    csvMaxRows: "Hasta 200 filas por archivo",
    csvValidRows: (n: number) => `${n} válidas`,
    csvBadRows: (n: number) => `${n} con error`,
    btnChangeFile: "Cambiar archivo",
    csvColTitle: "Título",
    csvColDesc: "Descripción",
    csvColMonthWeekDay: "Mes/Semana/Día",
    csvColHour: "Hora",
    csvColStatus: "Estado",
    csvMissingCols: "Faltan columnas obligatorias: title y description.",
    csvNoData: "No se encontraron filas con datos.",
    csvTooManyRows: (n: number) => `Demasiadas filas (${n}). El máximo por importación es 200.`,
    csvReadError: "No se pudo leer el archivo CSV",
    csvReadFileError: "No se pudo leer el archivo",
    csvCampaignIdInvalid: (id: string) => `campaignId inválido: "${id}"`,
    csvTemplateIdInvalid: (id: string) => `templateId inválido: "${id}"`,
    toastDuplicateError: "Error al duplicar el video",
    toastDuplicateFailed: "No se pudo duplicar el video",
    toastDuplicatedAs: (title: string) => `Duplicado como "${title}"`,
    toastBulkDeleted: (n: number) => `${n} videos eliminados`,
    toastBulkUpdateError: "Error al actualizar",
    toastBulkUpdated: (n: number) => `${n} videos actualizados`,
    toastBulkUpdateFailed: "No se pudieron actualizar los videos",
    toastSaveViewFailed: "Error al guardar la vista",
    toastDeleteViewFailed: "Error al eliminar la vista",
    toastViewNameRequired: "Ingresa un nombre para la vista",
    toastMonthRequired: "Ingresa un mes (ej. Mes 1)",
    toastDateTimeRequired: "Selecciona fecha y hora",
    toastBulkScheduled: (n: number) => `${n} videos programados`,
    toastBulkScheduleFailed: "No se pudieron programar los videos",
    toastBulkGenMax: (n: number) => `Selecciona máximo 50 videos para generar descripciones (tienes ${n})`,
    toastBulkGenResult: (ok: number, failed: number) => `Descripciones generadas: ${ok}${failed ? ` · Fallaron: ${failed}` : ""}`,
    toastBulkGenFailed: "No se pudieron generar las descripciones",
    toastCreateFailed: (status: number) => `No se pudo crear el video (HTTP ${status})`,
    toastSaveFailed: "Error al guardar",
    toastDeleteFailed: "Error al eliminar",
    coverSizeError: "La portada no puede superar 8MB",
    coverReadError: "No se pudo leer el archivo",
    coverUploadFailed: "No se pudo subir la portada",
    toastCoverUploadError: "Error al subir portada",
    clearCoverFailed: "No se pudo quitar la portada",
    toastClearCoverError: "Error al quitar portada",
    autoSaveErrorLabel: "Error al guardar",
    autoSavedLabel: "Guardado",
    autoSavingLabel: "Guardando...",
    autoUnsavedLabel: "Sin guardar",
    autoSavedSecsAgo: (n: number) => `Guardado hace ${n}s`,
    autoSavedMinAgo: (n: number) => `Guardado hace ${Math.floor(n)} min`,
    toastUploadingVideo: "Subiendo video...",
    toastVideoUploaded: "Video subido",
    errorLinkVideo: (status: number) => `Error vinculando video (HTTP ${status})`,
    errorUploadVideo: (status: number) => `Error subiendo video (HTTP ${status})`,
    drivePickerTitle: "Seleccionar Video desde Drive",
    driveAccessError: "Error al acceder a Google Drive",
    driveUnknownError: "Error desconocido",
    driveSignOutHint: "Cierra sesión y vuelve a iniciar para otorgar permisos de Drive.",
    driveEmptyFolder: "No hay carpetas ni videos en esta ubicación",
    driveSelect: "Seleccionar",
    driveLoadFilesError: "Error al cargar archivos",
    driveLoadFoldersError: "Error al cargar carpetas",
    ariaClearSearch: "Limpiar búsqueda",
    ariaDeleteView: (name: string) => `Eliminar vista ${name}`,
    ariaBulkMonth: "Asignar mes a la selección",
    ariaBulkSchedule: "Programar selección en lote",
    ariaViewStats: "Ver estadísticas",
    ariaRemixDuplicate: "Duplicar como remix (copia portada y archivo, descripciones en blanco)",
    // Video list
    noMatchFilters: "Ningún video coincide con tus filtros.",
    btnClearFilters: "Limpiar filtros",
    selectedCountLabel: (n: number) => `${n} seleccionado${n === 1 ? "" : "s"}`,
    videosCountLabel: (n: number) => `${n} video${n === 1 ? "" : "s"}`,
    showingCount: (filtered: number, total: number) => `Mostrando ${filtered} de ${total}`,
    // File validation
    invalidVideoFile: (type: string) => `El archivo no es un video válido (${type || "tipo desconocido"}).`,
    videoFileTooLarge: (sizeMB: string, maxMB: number) => `El video pesa ${sizeMB} MB. Máximo permitido: ${maxMB} MB.`,
    videoTitlePlaceholder: "Ej: Setup minimalista 2024",
    weekAbbrs: ["Sem 1", "Sem 2", "Sem 3", "Sem 4", "Sem 5"],
    labelHour: "Hora",
    errorLinkFallback: "Error al vincular",
    // Publish/upload error fallbacks
    errorServer: (status: number) => `Error del servidor (${status}).`,
    errorServerReload: (status: number) => `Error del servidor (${status}). Recarga la página e intenta de nuevo.`,
    errorUnknown: "Error desconocido",
    errorNetwork: "Error de red",
    // Comments & approval
    dateLocale: "es-ES",
    commentsTitle: "Comentarios del equipo",
    commentsLoading: "Cargando…",
    commentsEmpty: "Aún no hay comentarios. Sé el primero en abrir la conversación.",
    userFallback: "Usuario",
    commentsSubmit: "Comentar",
    ariaDeleteComment: "Eliminar comentario",
    approvalHistoryTitle: "Historial de aprobación",
    approvalEmpty: "Sin solicitudes de revisión todavía.",
    statusApproved: "Aprobado",
    statusChanges: "Cambios",
    statusPending: "Pendiente",
    approvalRequestedBy: (name: string) => `Solicitada por ${name}`,
    // Bulk selection bar
    bulkBarLabel: (n: number) => n === 1 ? "1 video seleccionado" : `${n} videos seleccionados`,
    // Keyboard save toast
    toastNoChanges: "Sin cambios pendientes",
    // Card badge
    badgeNoDescriptions: "Sin descripciones",
    // Cover image alt
    altCover: "Portada",
    // PDF export
    alertPdfExportFailed: (msg: string) => `No se pudo exportar el PDF: ${msg}`,
    // Approval/review toasts
    toastVideoApproved: "Video aprobado",
    toastChangesRequested: "Cambios solicitados",
    toastApprovedButNotScheduled: "Aprobado, pero no se pudo programar",
    toastApprovedAndScheduled: "Aprobado y programado",
    toastApprovedChooseDate: "Aprobado · elige fecha para programar",
    // Studio upload internals
    studioChunkError: (part: number, total: number) => `Error parte ${part}/${total}`,
    studioChunkProgress: (part: number, total: number) => `Subiendo ${part}/${total}...`,
    studioServerError: "Error del servidor",
    studioUploadErrorGeneric: (title: string) => `Error subiendo "${title}"`,
    studioLoadIdeasError: "Error al cargar ideas",
    studioLoadStatsError: "Error al cargar stats",
    studioMarkRecordedError: "Error al marcar grabado",
    // Studio review/upload screen
    studioSendVideoTitle: "Enviar video",
    studioDriveNameLabel: "Nombre en Google Drive",
    studioDriveNamePlaceholder: "Nombre del video...",
    studioWaMessageLabel: "Mensaje de WhatsApp (opcional)",
    studioWaMessagePlaceholder: "Mensaje adicional para WhatsApp...",
    studioAutoEditLabel: "Auto-Editar",
    studioAutoEditDesc: "Recorte automático + portada",
    studioSubtitlesLabel: "Subtítulos",
    studioSubtitlesDesc: "Texto animado sobre el video",
    studioPublishTiktokLabel: "Publicar en TikTok ahora",
    studioPublishTiktokDesc: "Sube el video a TikTok como borrador al enviar",
    studioEditVideoTitle: "Editar video",
    studioNext: "Siguiente",
    studioPreparingVideo: "Preparando video...",
    // Wizard AI generation
    errorGeneratingDescriptions: "Error generando descripciones",
    // Upload cancel sentinel
    uploadCancelledMsg: "Subida cancelada",
  },

  en: {
    // Login
    loginSubtitle: "Content management panel",
    loginGoogle: "Sign in with Google",
    loginTestLink: "Sign in with test account",
    loginTestLabel: "Test account",
    loginUser: "Username",
    loginPassword: "Password",
    loginEnter: "Sign in",
    loginOnlyAuth: "Only authorized users can access",
    loginAgree: "By signing in, you agree to our",
    loginTerms: "Terms of Service",
    loginAnd: "and",
    loginPrivacy: "Privacy Policy",
    loginConnError: "Connection error",

    // Nav
    navHome: "Home",
    navPosts: "Posts",
    navAccounts: "Social Accounts",
    navVideos: "Video Manager",
    navInsights: "Insights",
    navLibrary: "Library",
    navCovers: "Covers",
    navStories: "Stories",
    navDescriptions: "Descriptions",
    navDrive: "Drive",
    navStudio: "Studio",
    navTranscriber: "Transcriber",
    navTeam: "Team",
    navHelp: "Help",
    navSettings: "Settings",
    navHub: "Executive Hub",
    navLogout: "Sign Out",
    navSearch: "Search or run...",
    navMenu: "Menu",
    navMore: "More",
    navCloseMenu: "Close menu",
    navOpenMenu: "Open menu",

    // Ajustes
    ajustesTitle: "Settings",
    ajustesSubtitle: "Manage API credentials for each social network. Values are encrypted with AES-256-GCM before being saved to the database.",
    ajustesSecurity: "Secure storage",
    ajustesSecurityDesc: "Values are encrypted before being saved. They are never shown in plaintext — you can only overwrite or delete them. Credentials marked as 'Environment' are set on the server and cannot be edited here.",

    // Cuentas
    cuentasTitle: "Social Accounts",
    cuentasSubtitle: "Connect your social networks to publish and pull stats to your Home.",
    cuentasHint: "Connect each network to publish and pull analytics. Some networks (Facebook, Instagram) use server credentials: they appear connected if the administrator configured the corresponding keys.",
    cuentasNoConnected: "No social networks connected yet",
    cuentasNoConnectedDesc: "Start by connecting at least one network below. Each network enables publishing videos, descriptions and stories on its platform.",
    cuentasConnect: "Connect",
    cuentasDisconnect: "Disconnect",
    cuentasReconnect: "Reconnect now",
    cuentasRefresh: "Refresh status",
    cuentasNotConnected: "Not connected",
    cuentasNoSession: "No active session",
    cuentasNoMethod: "No connection method available.",
    cuentasServerManaged: "Configure credentials in the server secrets.",

    // State badges
    badgeActive: "Active",
    badgeExpiring: "Expiring",
    badgeExpired: "Expired",
    badgeRevoked: "Revoked",
    badgeUnknown: "Unknown",

    // Expiry messages
    expiresOn: "Expires on",
    expiringSoon: (days: number) => `Session expires in ${days} day${days === 1 ? "" : "s"}. Reconnect soon to avoid failures.`,
    sessionInvalid: "Session is no longer valid. Reconnect your account to resume publishing.",

    // Network descriptions
    descFacebook: "Facebook Page connected at server level",
    descInstagram: "Instagram Business account linked to the Page",
    descLinkedin: "Personal profile or Company Page",
    descX: "X (Twitter) account",
    descTiktok: "Sandbox mode: video arrives as a draft",
    descYoutube: "Connect to upload videos to YouTube, access Drive and Google Calendar",

    // Network server notes
    noteFacebook: "Facebook uses permanent System User credentials configured on the server.",
    noteInstagram: "Instagram requires Meta server-level credentials (INSTAGRAM_ACCESS_TOKEN). Ask the administrator to configure them in the project secrets.",

    // TikTok meta
    tiktokSandbox: "Connected (sandbox)",

    // Instagram meta
    followers: "followers",
    posts: "posts",

    // LinkedIn
    linkedinChangeIdentity: "Change publishing identity",
    linkedinChooseHow: "Choose how to publish on LinkedIn:",
    linkedinPersonal: "Personal profile",
    linkedinSearching: "Looking for pages...",
    linkedinEnterPage: "Enter the URL or name of your LinkedIn Company Page:",
    linkedinNotFound: "Page not found. Check the exact name at linkedin.com/company/...",
    linkedinSelect: "Select →",
    linkedinCompanyPage: "Company page",

    // X
    xConnected: "X account connected",

    // Facebook
    fbConnected: "Facebook Page connected",

    // LinkedIn connected meta
    linkedinCompanyPageMeta: "Company page",
    linkedinPersonalMeta: "Personal profile",

    // Lang toggle
    langLabel: "ES",

    // ── Videos page ──────────────────────────────────────────────
    stepInfo: "Basic Info",
    stepInfoShort: "Info",
    stepCover: "Cover",
    stepCoverShort: "Cover",
    stepTikTokInstagram: "TikTok & Instagram",
    stepTikTokShort: "TikTok/IG",
    stepYouTube: "YouTube",
    stepYouTubeShort: "YouTube",
    stepLinkedInX: "LinkedIn & X",
    stepLinkedInXShort: "LinkedIn/X",
    stepReview: "Review & Schedule",
    stepReviewShort: "Schedule",
    stepComments: "Comments & Approval",
    stepCommentsShort: "Comments",

    searchPlaceholder: "Search by title, description or network...",
    filterAllStatuses: "All statuses",
    filterDraft: "Draft",
    filterCoverReady: "Cover ready",
    filterScheduled: "Scheduled",
    filterPublished: "Published",
    filterPartial: "Partial",
    filterError: "Error",
    filterAllNetworks: "All networks",
    filterAllMonths: "All months",
    filterAllCampaigns: "All campaigns",
    filterNoCampaign: "No campaign",
    filterAllTemplates: "All templates",
    filterNoTemplate: "No template",
    filterClear: "Clear",
    filterClearFilters: "Clear filters",
    noVideos: "No videos yet",
    noVideosDesc: "Create your first video. We'll guide you step by step: info, cover, per-network descriptions, and final review.",
    createFirstVideo: "Create first video",
    noResults: "No videos match your filters.",
    showingOf: (showing: number, total: number) => `Showing ${showing} of ${total}`,
    videosSelected: (n: number) => `${n} selected`,
    videosCount: (n: number) => `${n} video${n === 1 ? "" : "s"}`,

    statusPublished: "Published",
    statusPartial: "Partial",
    statusError: "Error",
    statusScheduled: "Scheduled",
    statusReady: "Ready",
    statusDraft: "Draft",
    statusComplete: (pct: number) => `${pct}% complete`,

    wizardNewVideo: "New Video",
    wizardCompleteAll: "Complete all steps to schedule across all 6 platforms",
    wizardAutoGenerating: "Generating AI content for all platforms...",
    wizardSaving: "Saving",
    wizardUnsaved: "Unsaved",
    wizardSavingTooltip: "Saving...",
    wizardUnsavedTooltip: "There are unsaved changes",
    wizardBack: "Back to list",
    wizardBackShort: "Back",
    wizardDelete: "Delete",

    btnSave: "Save",
    btnCancel: "Cancel",
    btnContinue: "Continue",
    btnContinueWithoutCover: "Continue without cover",
    btnCreateContinue: "Create & Continue",
    btnSaveContinue: "Save & Continue",
    btnPrev: "Previous",
    btnGenerate: "Generate with AI",
    btnGenerating: "Generating...",
    btnRegenerate: "Regenerate with AI",
    btnUpload: "Upload cover",
    btnUploading: "Uploading...",
    btnReplace: "Replace",
    btnRemove: "Remove",
    btnCopyAll: "Copy all",
    btnDownloadTxt: "Download .txt",
    btnExportPdf: "Export .pdf",
    btnExportingPdf: "Exporting...",
    btnGenerateAI: "✨ Generate with AI",
    btnSchedule: "Schedule",
    btnCopy: "Copy",
    btnChange: "Change",
    btnViewHelp: "View help",

    coverTitle: "Video Cover",
    coverOptional: "(optional)",
    coverSubtitle: "Upload your own cover or generate one with AI. You can skip this and come back later.",
    coverReady: "Cover ready",
    coverHowItLooks: "How it will look on each network",
    coverPromptLabel: "Custom AI prompt",
    coverPromptActive: "Active",
    coverPromptDesc: "Write specific instructions (style, colors, on-screen text, scene). Overrides the default prompt. Leave empty to revert to automatic style.",
    coverGenerateWithPrompt: "Generate with this prompt",
    coverFileHint: "PNG, JPG or WEBP · Cover is optional, you can continue without it.",

    stepInfoTitle: "Basic Info",
    stepInfoSubtitle: "Enter the main information about the video",
    videoTitleLabel: "Video Title",
    videoDescLabel: "General Description",
    saveViewBtn: "Save current view",
    toastVistaSaved: "View saved",
    toastVistaDeleted: "View deleted",
    toastVideoCreated: "Video created",
    toastVideoCreatedDesc: "Generating AI content in the background...",
    toastVideoDeleted: "Video deleted",
    toastCoverGenerated: "Cover generated",
    toastCoverUploaded: "Cover uploaded",
    toastRetryFromInfo: "Try again from the Info step.",
    fromGoogleDrive: "From Google Drive",
    fromGoogleDriveHint: "Select a video from your Drive",
    uploadOrDrag: "Upload or drag file",
    uploadOrDragHint: (mb: number) => `MP4, MOV · Max ${mb} MB`,
    linkingFromDrive: "Linking from Drive...",
    uploadingToDrive: "Uploading to Google Drive...",
    uploadCancel: "Cancel",
    preparing: "Preparing...",

    stepTikTokTitle: "TikTok & Instagram",
    stepTikTokSubtitle: "Write descriptions for TikTok and Instagram. Include hashtags and emojis.",
    genTikTokPlaceholder: "TikTok description",
    genInstagramPlaceholder: "Instagram description",
    tiktokCharHint: (n: number) => `Maximum 2200 characters · ${n}/2200`,
    instagramCharHint: (n: number) => `Maximum 2200 characters · ${n}/2200`,

    stepYouTubeTitle: "YouTube",
    stepYouTubeSubtitle: "Title and description for YouTube Shorts. The title is different from TikTok/Instagram.",
    ytTitleLabel: "YouTube Title",
    ytDescLabel: "YouTube Description",
    genYTTitlePlaceholder: "YouTube title",
    genYTDescPlaceholder: "YouTube description",
    ytTitlePlaceholder: "Optimized title for YouTube (max 100 characters)",
    ytTitleHint: (n: number) => `${n}/100 characters`,
    ytDescHint: (n: number) => `${n}/5000 characters`,

    stepLinkedInXTitle: "LinkedIn, X & Facebook",
    stepLinkedInXSubtitle: "Text for LinkedIn (max 3000), X (max 280) and Facebook (max 500). Facebook is optional.",
    fbDescOptional: "(optional)",
    genLinkedInPlaceholder: "LinkedIn description",
    genXPlaceholder: "X tweet",
    linkedinCharHint: (n: number) => `Maximum 3000 characters · ${n}/3000`,
    xCharHint: (n: number) => `Maximum 280 characters · ${n}/280`,
    fbCharHint: (n: number) => `Maximum 500 characters · ${n}/500`,

    reviewTitle: "Review & Schedule",
    reviewSubtitle: "Review everything before scheduling across all 6 platforms",
    reviewReady: "Ready",
    reviewPending: "Pending",
    reviewScheduled: "Scheduled",
    reviewIncomplete: "Missing information",
    reviewIncompleteDesc: "Complete all previous steps before scheduling",
    reviewPartiallyPublished: "Partially published",
    reviewPublishErrors: "There were publishing errors",
    reviewScheduledSuccess: "Scheduled on configured platforms",
    reviewScheduledTime: "Scheduled time:",
    reviewImmediateUpload: "Immediate Upload",
    reviewImmediateSubtitle: "· Uploads now, not at the scheduled time",
    reviewImmediateSubtitleIG: "· Uploads now as a public Reel",
    reviewUploadYTNow: "Upload to YouTube now",
    reviewUploadTTNow: "Upload to TikTok now",
    reviewUploadIGNow: "Upload to Instagram now",
    reviewUploadPrivateYT: (name: string) => `Upload "${name}" as private Short`,
    reviewUploadPrivateTT: (name: string) => `Upload "${name}" as private`,
    reviewUploadReel: (name: string) => `Upload "${name}" as Reel`,
    reviewSelectFromDrive: "Select a video from Drive",
    reviewUploadFromDrive: "Upload from Drive",
    reviewFromDrive: "From Drive",
    reviewUploading: "Uploading...",
    reviewUploadedToYT: "Uploaded to YouTube",
    reviewUploadedToTT: "Uploaded to TikTok",
    reviewUploadedToIG: "Uploaded to Instagram",
    reviewSentToTT: "Sent",
    reviewPublishedIG: "Published",
    reviewThumbnailApplied: "✓ Cover applied as thumbnail",
    reviewThumbnailError: (e: string) => `⚠ Cover not applied: ${e}`,
    reviewViewOnYT: "View on YouTube",
    reviewTTSuccessTitle: "Successfully uploaded to TikTok",
    reviewTTProcessing: "Processing on TikTok…",
    reviewTTPublished: "Published on TikTok",
    reviewTTFailed: "TikTok processing failed",
    reviewTTPollingStatus: "Checking status",
    reviewIGSuccessTitle: "Successfully uploaded to Instagram",
    reviewIncludeFacebook: "Include Facebook",

    saveViewPlaceholder: "View name",

    // ── Studio page ──────────────────────────────────────────────
    studioListening: "Listening",
    studioEndOfScript: "END OF SCRIPT",
    studioMarkedRecorded: "Done, recorded",
    studioSlow: "Slow",
    studioFast: "Fast",
    studioSpeakFollow: "Speak and the script follows you",
    studioActivatingMic: "Activating microphone...",
    studioCameraError: "Failed to start camera",
    studioCameraPermission: "Check camera permissions in your browser or app settings",
    studioCameraRetry: "Retry",
    studioCameraBack: "Back",
    studioCameraNotAvailable: "Camera not available in this browser",
    studioCameraTimeout: "Camera took too long to respond",
    studioInitializingCamera: "Starting camera...",
    studioInitializingCameraHint: "Accept permissions if prompted",
    studioUploadToDrive: "Upload to Drive",
    studioDiscard: "Discard",
    studioExclude: "Exclude",
    studioInclude: "Include",
    studioVoiceReset: "Restarting",
    studioVoiceRetry: "Retrying clip",
    studioProcessingDrive: "Processing in Drive...",
    studioUploadingBg: "Uploading in background",
    studioUploadingBgDesc: (name: string) => `"${name}" is uploading. Choose another video to record.`,
    studioUploadedToDrive: (title: string, day: string) => `"${title}" ${day ? `uploaded → ${day}` : "uploaded"}`,
    studioUploadErrorDrive: (title: string) => `"${title}" ERROR uploading`,
    studioVideoMarkedTitle: "Video marked as recorded",
    studioScriptCopied: "Script copied to clipboard",
    studioIdeaDeleted: "Idea deleted",
    studioExcellent: "Excellent",
    studioVideoMarkedMsg: "Video marked as recorded",
    studioStreak: (n: number) => `Streak: ${n} days`,
    studioFreeRecord: "Free recording",
    studioNoScript: "No script, just you and the camera",
    studioDayDest: "Drive destination",
    studioDayAuto: "Day: Automatic",
    studioDayLunes: "Monday",
    studioDayMartes: "Tuesday",
    studioDayMiercoles: "Wednesday",
    studioDayJueves: "Thursday",
    studioDayViernes: "Friday",
    studioDaySabado: "Saturday",
    studioDayDomingo: "Sunday",
    studioPublishTime: (time: string) => `Publish time: ${time} hrs`,
    studioRacha: "Streak",
    studioSemana: "Week",
    studioMes: "Month",
    studioDeleting: "Deleting...",
    studioDelete: "Delete",
    studioEmptyTitle: "Your studio is empty",
    studioEmptyDesc: `Go to the "AI Ideas" tab, generate video ideas and save the ones you like with the bookmark. They will appear here ready to record.`,
    studioMotivational: [
      "Today is a great day to create content",
      "Your audience is waiting for your next video",
      "Consistency is the key to success",
      "Every video brings you closer to more clients",
      "The content you create today sells tomorrow",
      "One video a day keeps the algorithm happy",
      "Your brand grows with every video you record",
    ],
    videoLinked: "Video linked",
    noVideosTitle: "No videos yet",
    studioIdeasTab: "AI Ideas",
    studioTodayHint: (day: string, hour: number) => `Today: ${day} (${hour}:00 hrs)`,
    studioReadyToRecord: "Ready to record",
    studioRecordedCount: (n: number) => `Recorded (${n})`,
    studioDeleteIdeaTitle: "Delete idea",
    studioDeleteIdeaDesc: "This action cannot be undone",
    toastInvalidFile: "Invalid file",
    toastUploadError: "Error uploading video",
    toastUploadCancelled: "Upload cancelled",
    bulkChangeStatus: "Change status...",
    bulkAssignMonth: "Assign month",
    autoGenLabel: (label: string) => `Generating ${label} with AI...`,
    descLabelTikTok: "TikTok description",
    descLabelInstagram: "Instagram description",
    descLabelLinkedIn: "LinkedIn description",
    descLabelYouTube: "YouTube description",
    descLabelX: "X tweet",
    statViews: "Views",
    statLikes: "Likes",
    statComments: "Comments",
    statDuration: "Avg. duration",
    statPlays: "Plays",
    statReach: "Reach",
    statImpressions: "Impressions",
    statClicks: "Clicks",
    statReactions: "Reactions",
    statShares: "Shares",
    statRetweets: "Retweets",
    statReplies: "Replies",
    statQuotes: "Quotes",
    wfBorrador: "Draft",
    wfEnRevision: "In Review",
    wfAprobado: "Approved",
    wfProgramado: "Scheduled",
    wfPublicado: "Published",
    commentsPlaceholder: "Write a comment… use @email to mention someone",
    stepTikTokCardTitle: "TikTok & Instagram",
    stepLinkedInXCardTitle: "LinkedIn, X & Facebook",
    stepLinkedInXCardSubtitle: "Text for LinkedIn (max 3000), X (max 280) and Facebook (max 500). Facebook is optional.",
    ytTitlePlaceholderFull: "Optimized title for YouTube (max 100 characters)",
    ytDescPlaceholderFull: "YouTube description",
    secondaryViewHelp: "View help",
    viewNamePlaceholder: "View name",
    csvImportTitle: "Import videos from CSV",
    csvImporting: "Importing...",
    csvImportDone: "Import completed",
    csvImportBtn: (n: number) => `Import ${n} video${n === 1 ? "" : "s"}`,
    reviewAssignedTo: (name: string) => `Review assigned to ${name}`,
    btnComments: "Comments",
    btnRequestReview: "Request review",
    btnRequestChanges: "Request changes",
    btnApprove: "Approve",
    btnApproveSchedule: "Approve & schedule",
    btnApproveDirect: "Approve directly",
    labelReviewer: "Reviewer",
    selectReviewer: "Select a reviewer...",
    toastSelectReviewer: "Please select a reviewer",
    toastReviewRequested: "Review requested",
    csvNoValidRows: "No valid rows to import",
    csvPartialError: (created: number, errors: number) => `${created} imported, ${errors} with errors`,
    csvImportFailed: "Import failed",
    csvImportedDraft: (n: number) => `${n} video${n === 1 ? "" : "s"} imported as draft`,
    csvImportError: "Import error",
    csvRowMissingTitle: "Missing title",
    csvRowMissingDesc: "Missing description",
    csvRowTitleTooLong: "Title too long (max 240)",
    toastCompleteTitle: "Please fill in the video title",
    statErrorMsg: "Could not load metrics",
    toastDeleteVideosError: "Error deleting videos",
    toastDeleteVideosFailed: "Could not delete videos",
    toastDeleteVideoError: "Could not delete video",
    toastCreateVideoError: "Error creating video",
    toastAttachError: "Could not attach video",
    toastScheduleError: "Could not schedule",
    toastMarkRecordedError: "Could not mark as recorded",
    toastDeleteIdeaError: "Error deleting idea",
    toastUndoError: "Could not undo",
    errorNoVideoFile: "No video file. Upload one in step 1.",
    errorNoVideoFileDrive: "No video file in Drive. Upload one first.",
    confirmDeleteVideo: "Delete this video?",
    confirmBulkDelete: (n: number) => `Delete ${n} video${n === 1 ? "" : "s"}? This cannot be undone.`,
    btnDelete: "Delete",
    ariaDeselect: (title: string) => `Deselect "${title}"`,
    ariaSelect: (title: string) => `Select "${title}"`,
    reviewNoteLabel: "Note (optional)",
    reviewNotePlaceholder: "What should the reviewer check?",
    reviewNoReviewers: "No reviewers assigned. Go to /equipo to assign one.",
    cameraError: "Could not access camera",
    recordingError: "Error during recording",
    recordingStartError: "Could not start recording",
    browserNoVideo: "Your browser does not support video recording",
    studioNoVideoToUpload: "No video to upload",
    studioUploading: (mb: string) => `Uploading (${mb} MB)...`,
    studioNoVideoRecorded: "No video was recorded",
    labelVideoFile: "Video File",
    videoUnsupported: "Your browser does not support video playback.",
    videoDriveSelected: "Drive video selected",
    videoSelected: "Video selected",
    videoAttachedFile: "Attached file",
    videoWillLinkOnSave: "Will be linked when saved",
    uploadPreparing: "Preparing...",
    uploadFromDrive: "From Google Drive",
    uploadFromDriveHint: "Select a video from your Drive",
    uploadSizeHint: (mb: number) => `MP4, MOV · Max ${mb} MB`,
    coverPromptTitle: "Custom AI Prompt",
    coverPromptPlaceholder: (title: string) => `E.g.: Vertical 9:16 cover, yellow flat vector style, fox with glasses pointing at a chart. Large text at top: "${title || "TITLE"}".`,
    btnGenerateWithPrompt: "Generate with this prompt",
    uploadNetworkError: "Network error during upload",
    uploadCancelledError: "Upload cancelled",
    csvEmptyError: "The CSV file is empty or only has headers.",
    toastSaveViewError: "Could not save view",
    toastSaveError: (status: number) => `Could not save (HTTP ${status})`,
    toastCoverError: "Error generating cover",
    toastCoverEmptyError: "Empty or invalid cover file",
    toastLoadStatsError: "Error loading stats",
    statDialogTitle: (title: string) => `Stats — ${title}`,
    toastAutoSaveError: "Auto-save failed",
    toastRetry: "Try again",
    toastScheduled: (platforms: string) => `Scheduled on ${platforms}!`,
    toastAutoUpload: (hour: string) => `Will auto-upload at ${hour}`,
    toastAutoUploadNow: "Will auto-upload now",
    platforms6: "6 platforms",
    platforms5: "5 platforms",
    videoDescPlaceholder: "What is the video about?",
    labelMonth: "Month",
    labelWeek: "Week",
    labelDay: "Day",
    monthAbbrs: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] as const,
    dayAbbrs: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"] as const,
    toastSavePromptError: "Could not save prompt",
    toastSavePromptErrorTitle: "Error saving prompt",
    uploadHttpError: (status: number) => `Upload error (HTTP ${status})`,
    teleprompterEnd: "END OF SCRIPT",
    btnMarkRecorded: "Done, recorded",
    videoRecordedLabel: "Video recorded",
    headerGestorVideos: "Video Manager",
    headerGestorDesc: "Your editor can complete each video step by step without leaving this page.",
    btnNewVideo: "New Video",
    savedViewsLabel: "Saved views",
    pendingReviewsLabel: "My pending reviews",
    noSavedViews: "No saved views yet. Apply filters and save one for quick access.",
    csvInstructions: "Upload a .csv file with title and description columns (optional: month, week, day, videoNumber, hour, campaignId, templateId). Videos are saved as draft.",
    btnTemplate: "Template",
    csvDragHere: "Drag your CSV here or click to select",
    csvMaxRows: "Up to 200 rows per file",
    csvValidRows: (n: number) => `${n} valid`,
    csvBadRows: (n: number) => `${n} with error`,
    btnChangeFile: "Change file",
    csvColTitle: "Title",
    csvColDesc: "Description",
    csvColMonthWeekDay: "Month/Week/Day",
    csvColHour: "Hour",
    csvColStatus: "Status",
    csvMissingCols: "Missing required columns: title and description.",
    csvNoData: "No data rows found.",
    csvTooManyRows: (n: number) => `Too many rows (${n}). Maximum is 200 per import.`,
    csvReadError: "Could not read CSV file",
    csvReadFileError: "Could not read file",
    csvCampaignIdInvalid: (id: string) => `Invalid campaignId: "${id}"`,
    csvTemplateIdInvalid: (id: string) => `Invalid templateId: "${id}"`,
    toastDuplicateError: "Error duplicating video",
    toastDuplicateFailed: "Could not duplicate video",
    toastDuplicatedAs: (title: string) => `Duplicated as "${title}"`,
    toastBulkDeleted: (n: number) => `${n} video${n === 1 ? "" : "s"} deleted`,
    toastBulkUpdateError: "Error updating",
    toastBulkUpdated: (n: number) => `${n} video${n === 1 ? "" : "s"} updated`,
    toastBulkUpdateFailed: "Could not update videos",
    toastSaveViewFailed: "Error saving view",
    toastDeleteViewFailed: "Error deleting view",
    toastViewNameRequired: "Enter a name for the view",
    toastMonthRequired: "Enter a month (e.g. Month 1)",
    toastDateTimeRequired: "Select a date and time",
    toastBulkScheduled: (n: number) => `${n} video${n === 1 ? "" : "s"} scheduled`,
    toastBulkScheduleFailed: "Could not schedule videos",
    toastBulkGenMax: (n: number) => `Select at most 50 videos to generate descriptions (you have ${n})`,
    toastBulkGenResult: (ok: number, failed: number) => `Descriptions generated: ${ok}${failed ? ` · Failed: ${failed}` : ""}`,
    toastBulkGenFailed: "Could not generate descriptions",
    toastCreateFailed: (status: number) => `Could not create video (HTTP ${status})`,
    toastSaveFailed: "Error saving",
    toastDeleteFailed: "Error deleting",
    coverSizeError: "Cover cannot exceed 8 MB",
    coverReadError: "Could not read file",
    coverUploadFailed: "Could not upload cover",
    toastCoverUploadError: "Error uploading cover",
    clearCoverFailed: "Could not remove cover",
    toastClearCoverError: "Error removing cover",
    autoSaveErrorLabel: "Error saving",
    autoSavedLabel: "Saved",
    autoSavingLabel: "Saving...",
    autoUnsavedLabel: "Unsaved",
    autoSavedSecsAgo: (n: number) => `Saved ${n}s ago`,
    autoSavedMinAgo: (n: number) => `Saved ${Math.floor(n)} min ago`,
    toastUploadingVideo: "Uploading video...",
    toastVideoUploaded: "Video uploaded",
    errorLinkVideo: (status: number) => `Error linking video (HTTP ${status})`,
    errorUploadVideo: (status: number) => `Error uploading video (HTTP ${status})`,
    drivePickerTitle: "Select Video from Drive",
    driveAccessError: "Error accessing Google Drive",
    driveUnknownError: "Unknown error",
    driveSignOutHint: "Sign out and sign back in to grant Drive permissions.",
    driveEmptyFolder: "No folders or videos at this location",
    driveSelect: "Select",
    driveLoadFilesError: "Error loading files",
    driveLoadFoldersError: "Error loading folders",
    ariaClearSearch: "Clear search",
    ariaDeleteView: (name: string) => `Delete view ${name}`,
    ariaBulkMonth: "Assign month to selection",
    ariaBulkSchedule: "Schedule selection in bulk",
    ariaViewStats: "View statistics",
    ariaRemixDuplicate: "Duplicate as remix (copies cover and file, clears descriptions)",
    // Video list
    noMatchFilters: "No videos match your filters.",
    btnClearFilters: "Clear filters",
    selectedCountLabel: (n: number) => `${n} selected`,
    videosCountLabel: (n: number) => `${n} video${n === 1 ? "" : "s"}`,
    showingCount: (filtered: number, total: number) => `Showing ${filtered} of ${total}`,
    // File validation
    invalidVideoFile: (type: string) => `The file is not a valid video (${type || "unknown type"}).`,
    videoFileTooLarge: (sizeMB: string, maxMB: number) => `The video is ${sizeMB} MB. Maximum allowed: ${maxMB} MB.`,
    videoTitlePlaceholder: "E.g.: Minimalist Setup 2024",
    weekAbbrs: ["Wk 1", "Wk 2", "Wk 3", "Wk 4", "Wk 5"],
    labelHour: "Hour",
    errorLinkFallback: "Link error",
    // Publish/upload error fallbacks
    errorServer: (status: number) => `Server error (${status}).`,
    errorServerReload: (status: number) => `Server error (${status}). Please reload the page and try again.`,
    errorUnknown: "Unknown error",
    errorNetwork: "Network error",
    // Comments & approval
    dateLocale: "en-US",
    commentsTitle: "Team comments",
    commentsLoading: "Loading…",
    commentsEmpty: "No comments yet. Be the first to start the conversation.",
    userFallback: "User",
    commentsSubmit: "Comment",
    ariaDeleteComment: "Delete comment",
    approvalHistoryTitle: "Approval history",
    approvalEmpty: "No review requests yet.",
    statusApproved: "Approved",
    statusChanges: "Changes",
    statusPending: "Pending",
    approvalRequestedBy: (name: string) => `Requested by ${name}`,
    // Bulk selection bar
    bulkBarLabel: (n: number) => n === 1 ? "1 video selected" : `${n} videos selected`,
    // Keyboard save toast
    toastNoChanges: "No pending changes",
    // Card badge
    badgeNoDescriptions: "No descriptions",
    // Cover image alt
    altCover: "Cover",
    // PDF export
    alertPdfExportFailed: (msg: string) => `Could not export PDF: ${msg}`,
    // Approval/review toasts
    toastVideoApproved: "Video approved",
    toastChangesRequested: "Changes requested",
    toastApprovedButNotScheduled: "Approved, but could not schedule",
    toastApprovedAndScheduled: "Approved and scheduled",
    toastApprovedChooseDate: "Approved · choose a date to schedule",
    // Studio upload internals
    studioChunkError: (part: number, total: number) => `Error uploading chunk ${part}/${total}`,
    studioChunkProgress: (part: number, total: number) => `Uploading ${part}/${total}...`,
    studioServerError: "Server error",
    studioUploadErrorGeneric: (title: string) => `Error uploading "${title}"`,
    studioLoadIdeasError: "Error loading ideas",
    studioLoadStatsError: "Error loading stats",
    studioMarkRecordedError: "Error marking as recorded",
    // Studio review/upload screen
    studioSendVideoTitle: "Send video",
    studioDriveNameLabel: "Google Drive name",
    studioDriveNamePlaceholder: "Video name...",
    studioWaMessageLabel: "WhatsApp message (optional)",
    studioWaMessagePlaceholder: "Additional WhatsApp message...",
    studioAutoEditLabel: "Auto-Edit",
    studioAutoEditDesc: "Auto crop + cover",
    studioSubtitlesLabel: "Subtitles",
    studioSubtitlesDesc: "Animated text on the video",
    studioPublishTiktokLabel: "Publish to TikTok now",
    studioPublishTiktokDesc: "Upload the video to TikTok as a draft when sending",
    studioEditVideoTitle: "Edit video",
    studioNext: "Next",
    studioPreparingVideo: "Preparing video...",
    // Wizard AI generation
    errorGeneratingDescriptions: "Error generating descriptions",
    // Upload cancel sentinel
    uploadCancelledMsg: "Upload cancelled",
  },
} as const;

type Translations = typeof T.es;

interface LangCtx {
  lang: Lang;
  t: Translations;
  toggleLang: () => void;
}

const LangContext = createContext<LangCtx>({
  lang: "es",
  t: T.es,
  toggleLang: () => {},
});

export function LangProvider({ children }: { children: ReactNode }) {
  const stored = (() => {
    try { return (localStorage.getItem("lang") as Lang) || "es"; } catch { return "es"; }
  })();
  const [lang, setLang] = useState<Lang>(stored === "en" ? "en" : "es");

  const toggleLang = useCallback(() => {
    setLang((l) => {
      const next = l === "es" ? "en" : "es";
      try { localStorage.setItem("lang", next); } catch {}
      return next;
    });
  }, []);

  return (
    <LangContext.Provider value={{ lang, t: T[lang] as typeof T.es, toggleLang }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
